title: Henry Piotrowski
logo: "/images/LinkedIn Picture.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/Henry-Piotrowski/">LinkedIn</a> 
  <br>
  <a href="pdf/Henry_Piotrowski_Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/henrypiotrowski/">GitHub</a>  
  
theme: jekyll-theme-minimal
